### ISSUE TITLE
accent--text not generated

### ISSUE THREAD

**Issue by nthibert** [nmsmith22389/vuetify-scss#13]
I am trying to use the switch component. To change the colour to active, the component uses `accent--text`. Not sure how this is achieved using this lib. I looked through a lot of the variables and seems like it's not there. Is there a way to set the active state to the primary colour?

**Comment by nmsmith22389** [comment]
Those styles are generated separately by Vuetify then injected into the DOM on page load.
_See [this page](https://vuetifyjs.com/en/framework/theme) for more info._

Since that's something handled inside Vuetify's javascript, it's not something this package handles. The only purpose of [vuetify-scss](https://github.com/nmsmith22389/vuetify-scss) is to make all of the Stylus styles available as SCSS.
