### ISSUE TITLE
Missing files , got reset.scss only (question)

### ISSUE THREAD

**Issue by vlrmprjct** [nmsmith22389/vuetify-scss#3]
According to the readme, i got the reset.scss only.

In my main (scss) file:
`@import '~vuetify-scss';`

All other files are missing.

**Comment by nmsmith22389** [comment]
Hey! Sorry it took me so long. It seems to work fine for me so I'm not quite sure what's going on. I'm working on getting this package updated to the latest Vuetify version over the next few days so hopefully that will sort it out. Otherwise double check that your build tools are recognizing and pulling that file in the right way. Maybe it's getting purged or the SCSS is getting lost when transpiled.

**Comment by nmsmith22389** [comment]
[vuetify-scss@v1.2.0](https://github.com/nmsmith22389/vuetify-scss/tree/v1.2.0) is now up to date with v1.3.0 of Vuetify.

Try the new version and see if you still have problems.

**Comment by nmsmith22389** [comment]
I'm going to assume this is fixed and close the issue. If you have any more problems let me know.

Thanks!
