### ISSUE TITLE
Missing .info .succes colors

### ISSUE THREAD

**Issue by intermundos** [nmsmith22389/vuetify-scss#5]
Hi,

Thank for this. Helps a lot. 

Hoverever, when I try to use let's say v-btn color=info no color is added to the button, I also could not find color settings reflecting status of the button. This applies to all components. 

Thanks in advance for help.

**Comment by nmsmith22389** [comment]
If you mean that the class selectors for the theme aren't matching up that's probably because the way the theme selectors are laid out recently changed and this package hasn't been updated for that yet. I'm working on getting those changes out in the next couple days. Thanks!

**Comment by intermundos** [comment]
Thanks for letting know. 

I also found that changing $button-background-color variable does not work. Do you want me to open a new issue?

**Comment by nmsmith22389** [comment]
It actually looks like Vuetify itself doesn't use that variable, and since my code pretty much matches theirs, neither does mine. I have no idea why. Maybe it's left over from an older version.

It looks like for the default button background color they use `map-get($material-light, app-bar)`.

Given that, it would probably be better to just use the color attribute detailed in the [button documentation](https://vuetifyjs.com/en/components/buttons) or write some custom SCSS to override it.
